## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#DB o laptop
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin1234
    #103.226.248.168
    url: jdbc:mysql://103.226.248.168:3306/ecomerce_prod?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    #DB o cong ty
    #spring:
    #  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: admin1234
    #    url: jdbc:mysql://localhost:3306/ecomerce_prod?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    # Khởi tạo cơ sở dữ liệu bằng cách sử dụng các tập lệnh SQL cơ bản!
    platform: demo
    initialization-mode: always
    continue-on-error: true
    #connection pool -----------------------------------------------
  #config upload file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    tomcat:
      initial-size: 15
      max-wait: 20000:50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      max-active: 50
  jpa:
    show-sql: true
    #    generate-ddl: true
    hibernate:
      ddl-auto: none   # cho phép Hibernate create , update, ... table schema Mysql.
    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
          dbc:
            time_zone: UTC
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  #SPRING SECURITY - truy vấn người dùng.
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?

# Thay đổi đường dẫn ngữ cảnh thay vì "http://localhost:PORT/"
server:
  servlet:
    contextPath: /api
  port: ${PORT:8080}
  # thời điểm token sẽ hết hạn và chuỗi jwtSecret!
jwtSecret: me.sunrise
jwtExpiration: 86400

